"""remove host from bindings

Revision ID: 579b3d25fe50
Revises: f2d2359b923a
Create Date: 2018-01-09 17:28:28.342513

"""

# revision identifiers, used by Alembic.
revision = '579b3d25fe50'
down_revision = 'f2d2359b923a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('netdev_bindings_fk_hostid', 'netdev_bindings', type_='foreignkey')
    op.drop_index('netdev_bindings_i_hostid', table_name='netdev_bindings')
    op.drop_column('netdev_bindings', 'hostid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netdev_bindings', sa.Column('hostid', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
    op.create_index('netdev_bindings_i_hostid', 'netdev_bindings', ['hostid'], unique=False)
    op.create_foreign_key('netdev_bindings_fk_hostid', 'netdev_bindings', 'hosts_def', ['hostid'], ['hostid'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###

