"""Initial revision

Revision ID: 16be1c0cddd0
Revises: 
Create Date: 2017-09-25 14:16:04.302368

"""

# revision identifiers, used by Alembic.
revision = '16be1c0cddd0'
down_revision = None
branch_labels = ('entities',)
depends_on = '5b808c910195'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from netprofile.db import ddl as npd
from netprofile.db import fields as npf

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities_flags_types',
    sa.Column('flagid', npf.UInt32(), npd.Comment('Entity flag type ID'), nullable=False, default=sa.Sequence('entities_flags_types_flagid_seq')),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('Entity flag type name'), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Entity flag type description'), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('flagid', name=op.f('entities_flags_types_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_flags_types', 'Entity flag types')
    op.create_index('entities_flags_types_u_name', 'entities_flags_types', ['name'], unique=True)
    op.create_table('entities_states',
    sa.Column('esid', npf.UInt32(), npd.Comment('Entity state ID'), nullable=False, default=sa.Sequence('entities_states_esid_seq')),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('Entity state name'), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Entity state description'), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('esid', name=op.f('entities_states_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_states', 'Entity states')
    op.create_index('entities_states_u_name', 'entities_states', ['name'], unique=True)
    op.create_table('entities_types',
    sa.Column('etypeid', npf.UInt32(), npd.Comment('Entity type ID'), nullable=False, default=sa.Sequence('entities_types_etypeid_seq', start=101, increment=1)),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('Entity type name'), nullable=False),
    sa.Column('npmodid', npf.UInt32(), npd.Comment('NetProfile module ID'), server_default=sa.text('1'), nullable=False),
    sa.Column('model', npf.ASCIIString(length=255), npd.Comment('ORM declarative model class name'), nullable=False),
    sa.Column('longname', sa.Unicode(length=255), npd.Comment('Long entity type name'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('plural', sa.Unicode(length=255), npd.Comment('Entity type plural string'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('root', npf.NPBoolean(), npd.Comment('Can be root node (can have no parent)'), server_default=npf.npbool(True), nullable=False),
    sa.Column('leaf', npf.NPBoolean(), npd.Comment("Leaf node (can't have any children)"), server_default=npf.npbool(False), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Entity type description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['npmodid'], ['np_modules.npmodid'], name='entities_types_fk_npmodid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('etypeid', name=op.f('entities_types_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_types', 'Entity types')
    op.create_index('entities_types_u_longname', 'entities_types', ['longname'], unique=True)
    op.create_index('entities_types_u_name', 'entities_types', ['name'], unique=True)
    op.create_index('entities_types_u_plural', 'entities_types', ['plural'], unique=True)
    op.create_index('entities_types_u_spec', 'entities_types', ['npmodid', 'model'], unique=True)
    op.create_table('entities_def',
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False, default=sa.Sequence('entities_def_entityid_seq')),
    sa.Column('parentid', npf.UInt32(), npd.Comment('Parent entity ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('nick', sa.Unicode(length=255), npd.Comment('Entity nickname'), nullable=False),
    sa.Column('esid', npf.UInt32(), npd.Comment('Entity state ID'), server_default=sa.text('1'), nullable=False),
    sa.Column('rdn', sa.Unicode(length=255), npd.Comment('Entity LDAP relative distinguished name'), nullable=False),
    sa.Column('etypeid', npf.UInt32(), npd.Comment('Entity type'), nullable=False),
    sa.Column('ctime', sa.TIMESTAMP(), npd.Comment('Creation timestamp'), server_default=FetchedValue(), nullable=True),
    sa.Column('mtime', sa.TIMESTAMP(), npd.Comment('Last modification timestamp'), server_default=npd.CurrentTimestampDefault(on_update=True), nullable=False),
    sa.Column('cby', npf.UInt32(), npd.Comment('Created by'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('mby', npf.UInt32(), npd.Comment('Modified by'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Entity description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['cby'], ['users.uid'], name='entities_def_fk_cby', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['esid'], ['entities_states.esid'], name='entities_def_fk_esid', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['etypeid'], ['entities_types.etypeid'], name='entities_def_fk_etypeid', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['mby'], ['users.uid'], name='entities_def_fk_mby', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parentid'], ['entities_def.entityid'], name='entities_def_fk_parentid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entityid', name=op.f('entities_def_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_def', 'Entities')
    op.create_trigger('netprofile_entities', 'entities_def', 'before', 'insert', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_def', 'before', 'update', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_def', 'after', 'insert', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_def', 'after', 'update', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_def', 'after', 'delete', '16be1c0cddd0')
    op.create_index('entities_def_i_cby', 'entities_def', ['cby'], unique=False)
    op.create_index('entities_def_i_esid', 'entities_def', ['esid'], unique=False)
    op.create_index('entities_def_i_mby', 'entities_def', ['mby'], unique=False)
    op.create_index('entities_def_i_nick', 'entities_def', ['nick'], unique=False)
    op.create_index('entities_def_i_parentid', 'entities_def', ['parentid'], unique=False)
    op.create_index('entities_def_u_nt', 'entities_def', ['etypeid', 'nick'], unique=True)
    op.create_table('addr_def',
    sa.Column('addrid', npf.UInt32(), npd.Comment('Address ID'), nullable=False, default=sa.Sequence('addr_def_addrid_seq')),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('atype', npf.DeclEnumType(name='AddressType', values=['home', 'work', 'post', 'parc', 'bill']), npd.Comment('Address type'), server_default=sa.text("'home'"), nullable=False),
    sa.Column('primary', npf.NPBoolean(), npd.Comment('Is address primary?'), server_default=npf.npbool(False), nullable=False),
    sa.Column('houseid', npf.UInt32(), npd.Comment('House ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('entrance', npf.UInt8(), npd.Comment('Entrance number'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('floor', npf.Int16(), npd.Comment('Floor number'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('flat', npf.UInt16(), npd.Comment('Flat number'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('entrycode', sa.Unicode(length=8), npd.Comment('Entry code'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('postindex', sa.Unicode(length=8), npd.Comment('Postal code'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Address description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='addr_def_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['houseid'], ['addr_houses.houseid'], name='addr_def_fk_houseid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('addrid', name=op.f('addr_def_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('addr_def', 'Addresses')
    op.create_index('addr_def_i_entityid', 'addr_def', ['entityid'], unique=False)
    op.create_index('addr_def_i_houseid', 'addr_def', ['houseid'], unique=False)
    op.create_table('addr_phones',
    sa.Column('phoneid', npf.UInt32(), npd.Comment('Phone ID'), nullable=False, default=sa.Sequence('addr_phones_phoneid_seq')),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('primary', npf.NPBoolean(), npd.Comment('Is phone primary?'), server_default=npf.npbool(False), nullable=False),
    sa.Column('ptype', npf.DeclEnumType(name='PhoneType', values=['home', 'cell', 'work', 'pager', 'fax', 'rec']), npd.Comment('Phone type'), server_default=sa.text("'home'"), nullable=False),
    sa.Column('num', npf.ASCIIString(length=255), npd.Comment('Phone number'), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Phone description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='addr_phones_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phoneid', name=op.f('addr_phones_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('addr_phones', 'Phone numbers')
    op.create_index('addr_def_i_entityid', 'addr_phones', ['entityid'], unique=False)
    op.create_index('addr_phones_i_num', 'addr_phones', ['num'], unique=False)
    op.create_table('entities_comments',
    sa.Column('ecid', npf.UInt32(), npd.Comment('Entity comment ID'), nullable=False, default=sa.Sequence('entities_comments_ecid_seq')),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(), npd.Comment('Time stamp'), server_default=npd.CurrentTimestampDefault(on_update=False), nullable=False),
    sa.Column('uid', npf.UInt32(), npd.Comment('User ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('obsolete', npf.NPBoolean(), npd.Comment('Is comment obsolete?'), server_default=npf.npbool(False), nullable=False),
    sa.Column('text', sa.UnicodeText(), npd.Comment('Entity comment text'), nullable=False),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_comments_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='entities_comments_fk_uid', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ecid', name=op.f('entities_comments_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_comments', 'Historic comments on entities')
    op.create_index('entities_comments_i_entityid', 'entities_comments', ['entityid'], unique=False)
    op.create_index('entities_comments_i_uid', 'entities_comments', ['uid'], unique=False)
    op.create_table('entities_comms',
    sa.Column('ecommid', npf.UInt32(), npd.Comment('Entity communication channel ID'), nullable=False, default=sa.Sequence('entities_comms_ecommid_seq')),
    sa.Column('commtid', npf.UInt32(), npd.Comment('Communication channel type ID'), nullable=False),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('primary', npf.NPBoolean(), npd.Comment('Primary flag'), server_default=npf.npbool(False), nullable=False),
    sa.Column('scope', npf.DeclEnumType(name='ContactInfoType', values=['home', 'work']), npd.Comment('Channel scope'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('value', sa.Unicode(length=255), npd.Comment('Channel address value'), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Communication channel description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['commtid'], ['comms_types.commtid'], name='entities_comms_fk_commtid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_comms_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ecommid', name=op.f('entities_comms_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_comms', 'Entity communication channels')
    op.create_index('entities_comms_i_commtid', 'entities_comms', ['commtid'], unique=False)
    op.create_index('entities_comms_i_entityid', 'entities_comms', ['entityid'], unique=False)
    op.create_table('entities_external',
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('Entity name'), nullable=False),
    sa.Column('address', sa.Unicode(length=255), npd.Comment('Entity address'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_external_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entityid', name=op.f('entities_external_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_external', 'External entities')
    op.create_trigger('netprofile_entities', 'entities_external', 'after', 'update', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_external', 'after', 'delete', '16be1c0cddd0')
    op.create_table('entities_flags_def',
    sa.Column('efid', npf.UInt32(), npd.Comment('Entity flag ID'), nullable=False, default=sa.Sequence('entities_flags_def_efid_seq')),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('flagid', npf.UInt32(), npd.Comment('Entity flag type ID'), nullable=False),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_flags_def_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flagid'], ['entities_flags_types.flagid'], name='entities_flags_types_fk_flagid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('efid', name=op.f('entities_flags_def_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_flags_def', 'Entity flag mappings')
    op.create_index('entities_flags_def_i_flagid', 'entities_flags_def', ['flagid'], unique=False)
    op.create_index('entities_flags_def_u_ef', 'entities_flags_def', ['entityid', 'flagid'], unique=True)
    op.create_table('entities_legal',
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('contractid', npf.UInt32(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('Legal name'), nullable=False),
    sa.Column('cp_name_family', sa.Unicode(length=255), npd.Comment('Contact person - family name'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('cp_name_given', sa.Unicode(length=255), npd.Comment('Contact person - given name'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('cp_name_middle', sa.Unicode(length=255), npd.Comment('Contact person - middle name'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('cp_title', sa.Unicode(length=255), npd.Comment('Contact person - title'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('cp_email', sa.Unicode(length=64), npd.Comment('Contact person - e-mail'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('homepage', sa.Unicode(length=64), npd.Comment('Homepage URL'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('address_legal', sa.Unicode(length=255), npd.Comment('Legal address'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('props_inn', sa.Unicode(length=64), npd.Comment('Properties - INN'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('props_kpp', sa.Unicode(length=64), npd.Comment('Properties - KPP'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('props_bic', sa.Unicode(length=64), npd.Comment('Properties - BIC'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('props_rs', sa.Unicode(length=64), npd.Comment('Properties - R/S'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('props_cs', sa.Unicode(length=64), npd.Comment('Properties - C/S'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('props_bank', sa.Unicode(length=255), npd.Comment('Properties - bank'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_legal_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entityid', name=op.f('entities_legal_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_legal', 'Legal entities')
    op.create_trigger('netprofile_entities', 'entities_legal', 'before', 'insert', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_legal', 'after', 'update', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_legal', 'after', 'delete', '16be1c0cddd0')
    op.create_index('entities_legal_u_contractid', 'entities_legal', ['contractid'], unique=True)
    op.create_index('entities_legal_u_name', 'entities_legal', ['name'], unique=True)
    op.create_table('entities_physical',
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('contractid', npf.UInt32(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('name_family', sa.Unicode(length=255), npd.Comment('Family name'), nullable=False),
    sa.Column('name_given', sa.Unicode(length=255), npd.Comment('Given name'), nullable=False),
    sa.Column('name_middle', sa.Unicode(length=255), npd.Comment('Middle name'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('gender', npf.DeclEnumType(name='Gender', values=['M', 'F', 'O', 'N']), npd.Comment('Gender'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('email', sa.Unicode(length=64), npd.Comment('External e-mail'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('homepage', sa.Unicode(length=64), npd.Comment('Homepage URL'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('birthdate', sa.Date(), npd.Comment('Birth date'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('pass_series', sa.Unicode(length=8), npd.Comment('Passport series'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('pass_num', sa.Unicode(length=8), npd.Comment('Passport number'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('pass_issuedby', sa.Unicode(length=255), npd.Comment('Passport issued by'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('pass_issuedate', sa.Date(), npd.Comment('Passport issue date'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_physical_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entityid', name=op.f('entities_physical_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_physical', 'Physical entities')
    op.create_trigger('netprofile_entities', 'entities_physical', 'before', 'insert', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_physical', 'after', 'update', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_physical', 'after', 'delete', '16be1c0cddd0')
    op.create_index('entities_physical_i_name_family', 'entities_physical', ['name_family'], unique=False)
    op.create_index('entities_physical_i_name_given', 'entities_physical', ['name_given'], unique=False)
    op.create_index('entities_physical_u_contractid', 'entities_physical', ['contractid'], unique=True)
    op.create_table('entities_structural',
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_structural_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entityid', name=op.f('entities_structural_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_structural', 'Structural entities')
    op.create_trigger('netprofile_entities', 'entities_structural', 'after', 'update', '16be1c0cddd0')
    op.create_trigger('netprofile_entities', 'entities_structural', 'after', 'delete', '16be1c0cddd0')
    op.create_table('entities_files',
    sa.Column('efid', npf.UInt32(), npd.Comment('Entity-file mapping ID'), nullable=False, default=sa.Sequence('entities_files_efid_seq')),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('fileid', npf.UInt32(), npd.Comment('File ID'), nullable=False),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='entities_files_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fileid'], ['files_def.fileid'], name='entities_files_fk_fileid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('efid', name=op.f('entities_files_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('entities_files', 'File mappings to entities')
    op.create_index('entities_files_i_fileid', 'entities_files', ['fileid'], unique=False)
    op.create_index('entities_files_u_efl', 'entities_files', ['entityid', 'fileid'], unique=True)
    op.create_view('entities_base', {'oracle': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL', 'mssql': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL', 'postgresql': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL', 'mysql': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL'}, check_option='CASCADED')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_view('entities_base', {'oracle': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL', 'mssql': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL', 'postgresql': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL', 'mysql': 'SELECT entities_def.entityid AS entityid, NULL AS parentid, entities_def.nick AS nick, entities_def.esid AS esid, entities_def.rdn AS rdn, entities_def.etypeid AS etypeid, entities_def.ctime AS ctime, entities_def.mtime AS mtime, entities_def.cby AS cby, entities_def.mby AS mby, entities_def.descr AS descr \nFROM entities_def \nWHERE entities_def.parentid IS NULL'}, check_option='CASCADED')
    op.drop_index('entities_files_u_efl', table_name='entities_files')
    op.drop_index('entities_files_i_fileid', table_name='entities_files')
    op.drop_table('entities_files')
    op.drop_table('entities_structural')
    op.drop_index('entities_physical_u_contractid', table_name='entities_physical')
    op.drop_index('entities_physical_i_name_given', table_name='entities_physical')
    op.drop_index('entities_physical_i_name_family', table_name='entities_physical')
    op.drop_table('entities_physical')
    op.drop_index('entities_legal_u_name', table_name='entities_legal')
    op.drop_index('entities_legal_u_contractid', table_name='entities_legal')
    op.drop_table('entities_legal')
    op.drop_index('entities_flags_def_u_ef', table_name='entities_flags_def')
    op.drop_index('entities_flags_def_i_flagid', table_name='entities_flags_def')
    op.drop_table('entities_flags_def')
    op.drop_table('entities_external')
    op.drop_index('entities_comms_i_entityid', table_name='entities_comms')
    op.drop_index('entities_comms_i_commtid', table_name='entities_comms')
    op.drop_table('entities_comms')
    op.drop_index('entities_comments_i_uid', table_name='entities_comments')
    op.drop_index('entities_comments_i_entityid', table_name='entities_comments')
    op.drop_table('entities_comments')
    op.drop_index('addr_phones_i_num', table_name='addr_phones')
    op.drop_index('addr_def_i_entityid', table_name='addr_phones')
    op.drop_table('addr_phones')
    op.drop_index('addr_def_i_houseid', table_name='addr_def')
    op.drop_index('addr_def_i_entityid', table_name='addr_def')
    op.drop_table('addr_def')
    op.drop_index('entities_def_u_nt', table_name='entities_def')
    op.drop_index('entities_def_i_parentid', table_name='entities_def')
    op.drop_index('entities_def_i_nick', table_name='entities_def')
    op.drop_index('entities_def_i_mby', table_name='entities_def')
    op.drop_index('entities_def_i_esid', table_name='entities_def')
    op.drop_index('entities_def_i_cby', table_name='entities_def')
    op.drop_table('entities_def')
    op.drop_index('entities_types_u_spec', table_name='entities_types')
    op.drop_index('entities_types_u_plural', table_name='entities_types')
    op.drop_index('entities_types_u_name', table_name='entities_types')
    op.drop_index('entities_types_u_longname', table_name='entities_types')
    op.drop_table('entities_types')
    op.drop_index('entities_states_u_name', table_name='entities_states')
    op.drop_table('entities_states')
    op.drop_index('entities_flags_types_u_name', table_name='entities_flags_types')
    op.drop_table('entities_flags_types')
    # ### end Alembic commands ###

