"""Nullable settings

Revision ID: 7e59384af3c9
Revises: 033d52604eac
Create Date: 2017-09-25 20:33:20.426669

"""

# revision identifiers, used by Alembic.
revision = '7e59384af3c9'
down_revision = '033d52604eac'
branch_labels = None
depends_on = None

from alembic import op
from netprofile.db import fields as npf

def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('np_settings_global', 'value',
               existing_type=npf.ASCIIString(255),
               nullable=True)
    op.alter_column('np_settings_user', 'value',
               existing_type=npf.ASCIIString(255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('np_settings_user', 'value',
               existing_type=npf.ASCIIString(255),
               nullable=False)
    op.alter_column('np_settings_global', 'value',
               existing_type=npf.ASCIIString(255),
               nullable=False)
    # ### end Alembic commands ###

