"""Ticket subscriptions

Revision ID: 3f17706add0f
Revises: d322f7ece4cd
Create Date: 2017-09-26 07:12:05.678038

"""

# revision identifiers, used by Alembic.
revision = '3f17706add0f'
down_revision = 'd322f7ece4cd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from netprofile.db import ddl as npd
from netprofile.db import fields as npf

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets_states_subscriptions',
    sa.Column('tstsubid', npf.UInt32(), npd.Comment('Ticket state subscription ID'), nullable=False, default=sa.Sequence('tickets_states_subscriptions_tstsubid_seq')),
    sa.Column('type', npf.DeclEnumType(name='TicketSubscriptionType', values=['U', 'G', 'E', 'A']), npd.Comment('Ticket state subscription type'), server_default=sa.text("'U'"), nullable=False),
    sa.Column('tstid', npf.UInt32(), npd.Comment('Ticket state ID'), nullable=False),
    sa.Column('uid', npf.UInt32(), npd.Comment('User ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('gid', npf.UInt32(), npd.Comment('Group ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('addr', sa.Unicode(length=255), npd.Comment('E-mail address'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='tickets_states_subscriptions_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gid'], ['groups.gid'], name='tickets_states_subscriptions_fk_gid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tstid'], ['tickets_states_types.tstid'], name='tickets_states_subscriptions_fk_tstid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='tickets_states_subscriptions_fk_uid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tstsubid', name=op.f('tickets_states_subscriptions_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tickets_states_subscriptions', 'Ticket state subscriptions')
    op.create_index('tickets_states_subscriptions_i_entityid', 'tickets_states_subscriptions', ['entityid'], unique=False)
    op.create_index('tickets_states_subscriptions_i_gid', 'tickets_states_subscriptions', ['gid'], unique=False)
    op.create_index('tickets_states_subscriptions_i_tstid', 'tickets_states_subscriptions', ['tstid'], unique=False)
    op.create_index('tickets_states_subscriptions_i_uid', 'tickets_states_subscriptions', ['uid'], unique=False)
    op.create_index('tickets_states_subscriptions_u_sub', 'tickets_states_subscriptions', ['tstid', 'uid', 'gid', 'entityid', 'addr'], unique=True)
    op.create_table('tickets_subscriptions',
    sa.Column('tsubid', npf.UInt32(), npd.Comment('Ticket subscription ID'), nullable=False, default=sa.Sequence('tickets_subscriptions_tsubid_seq')),
    sa.Column('type', npf.DeclEnumType(name='TicketSubscriptionType', values=['U', 'G', 'E', 'A']), npd.Comment('Ticket subscription type'), server_default=sa.text("'U'"), nullable=False),
    sa.Column('ticketid', npf.UInt32(), npd.Comment('Ticket ID'), nullable=False),
    sa.Column('uid', npf.UInt32(), npd.Comment('User ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('gid', npf.UInt32(), npd.Comment('Group ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('addr', sa.Unicode(length=255), npd.Comment('E-mail address'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('notify_change', npf.NPBoolean(), npd.Comment('Notify on any ticket change'), server_default=npf.npbool(False), nullable=False),
    sa.Column('notify_transition', npf.NPBoolean(), npd.Comment('Notify on ticket state transition'), server_default=npf.npbool(False), nullable=False),
    sa.Column('notify_close', npf.NPBoolean(), npd.Comment('Notify when ticket is closed (reaches end state)'), server_default=npf.npbool(False), nullable=False),
    sa.Column('issuer', npf.NPBoolean(), npd.Comment('Is ticket issued by this subscriber'), server_default=npf.npbool(False), nullable=False),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='tickets_subscriptions_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gid'], ['groups.gid'], name='tickets_subscriptions_fk_gid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets_def.ticketid'], name='tickets_subscriptions_fk_ticketid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='tickets_subscriptions_fk_uid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tsubid', name=op.f('tickets_subscriptions_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tickets_subscriptions', 'Ticket subscriptions')
    op.create_index('tickets_subscriptions_i_entityid', 'tickets_subscriptions', ['entityid'], unique=False)
    op.create_index('tickets_subscriptions_i_gid', 'tickets_subscriptions', ['gid'], unique=False)
    op.create_index('tickets_subscriptions_i_ticketid', 'tickets_subscriptions', ['ticketid'], unique=False)
    op.create_index('tickets_subscriptions_i_uid', 'tickets_subscriptions', ['uid'], unique=False)
    op.create_index('tickets_subscriptions_u_sub', 'tickets_subscriptions', ['ticketid', 'uid', 'gid', 'entityid', 'addr'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tickets_subscriptions_u_sub', table_name='tickets_subscriptions')
    op.drop_index('tickets_subscriptions_i_uid', table_name='tickets_subscriptions')
    op.drop_index('tickets_subscriptions_i_ticketid', table_name='tickets_subscriptions')
    op.drop_index('tickets_subscriptions_i_gid', table_name='tickets_subscriptions')
    op.drop_index('tickets_subscriptions_i_entityid', table_name='tickets_subscriptions')
    op.drop_table('tickets_subscriptions')
    op.drop_index('tickets_states_subscriptions_u_sub', table_name='tickets_states_subscriptions')
    op.drop_index('tickets_states_subscriptions_i_uid', table_name='tickets_states_subscriptions')
    op.drop_index('tickets_states_subscriptions_i_tstid', table_name='tickets_states_subscriptions')
    op.drop_index('tickets_states_subscriptions_i_gid', table_name='tickets_states_subscriptions')
    op.drop_index('tickets_states_subscriptions_i_entityid', table_name='tickets_states_subscriptions')
    op.drop_table('tickets_states_subscriptions')
    # ### end Alembic commands ###

