"""Initial revision

Revision ID: 1d7aad66a125
Revises: 
Create Date: 2017-09-25 16:34:31.297077

"""

# revision identifiers, used by Alembic.
revision = '1d7aad66a125'
down_revision = None
branch_labels = ('tv',)
depends_on = ['774d7277075e', '7829ac7b5ad0']

from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from netprofile.db import ddl as npd
from netprofile.db import fields as npf

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_subscriptions_types',
    sa.Column('tvsubtid', npf.UInt32(), npd.Comment('TV subscription type ID'), nullable=False, default=sa.Sequence('tv_subscriptions_types_tvsubtid_seq')),
    sa.Column('paidid', npf.UInt32(), npd.Comment('Paid service type ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('extid', npf.ASCIIString(length=255), npd.Comment('TV subscription external ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('TV subscription type name'), nullable=False),
    sa.Column('enabled', npf.NPBoolean(), npd.Comment('Is subscription type enabled'), server_default=npf.npbool(True), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['paidid'], ['paid_types.paidid'], name='tv_subscriptions_types_fk_paidid', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tvsubtid', name=op.f('tv_subscriptions_types_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tv_subscriptions_types', 'TV subscription types')
    op.create_index('tv_subscriptions_types_i_paidid', 'tv_subscriptions_types', ['paidid'], unique=False)
    op.create_index('tv_subscriptions_types_u_name', 'tv_subscriptions_types', ['name'], unique=True)
    op.create_table('tv_sources_def',
    sa.Column('tvsourceid', npf.UInt32(), npd.Comment('TV source ID'), nullable=False, default=sa.Sequence('tv_sources_def_tvsourceid_seq')),
    sa.Column('hostid', npf.UInt32(), npd.Comment('Gateway host ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('port', npf.UInt16(), npd.Comment('Gateway port number'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('TV source name'), nullable=False),
    sa.Column('enc', npf.ASCIIString(length=32), npd.Comment('Used text encoding'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('handler', npf.ASCIIString(length=255), npd.Comment('Gateway handler class'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('realtime', npf.NPBoolean(), npd.Comment('Update gateway in real time'), server_default=npf.npbool(True), nullable=False),
    sa.Column('polled', npf.NPBoolean(), npd.Comment('Update gateway in bulk'), server_default=npf.npbool(True), nullable=False),
    sa.Column('authuser', npf.ASCIIString(length=255), npd.Comment('Gateway username'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('authpass', npf.ASCIIString(length=255), npd.Comment('Gateway passphrase'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['hostid'], ['hosts_def.hostid'], name='tv_sources_def_fk_hostid', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tvsourceid', name=op.f('tv_sources_def_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tv_sources_def', 'Defined TV broadcast sources')
    op.create_index('tv_sources_def_i_hostid', 'tv_sources_def', ['hostid'], unique=False)
    op.create_index('tv_sources_def_u_name', 'tv_sources_def', ['name'], unique=True)
    op.create_table('tv_channels',
    sa.Column('tvchanid', npf.UInt32(), npd.Comment('TV channel ID'), nullable=False, default=sa.Sequence('tv_channels_tvchanid_seq')),
    sa.Column('tvsourceid', npf.UInt32(), npd.Comment('TV source ID'), nullable=False),
    sa.Column('extid', npf.ASCIIString(length=255), npd.Comment('TV channel external ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('name', sa.Unicode(length=255), npd.Comment('TV channel name'), nullable=False),
    sa.Column('descr', sa.UnicodeText(), npd.Comment('Description'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['tvsourceid'], ['tv_sources_def.tvsourceid'], name='tv_channels_fk_tvsourceid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tvchanid', name=op.f('tv_channels_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tv_channels', 'TV channels')
    op.create_index('tv_channels_u_channel', 'tv_channels', ['tvsourceid', 'name'], unique=True)
    op.create_table('tv_subscriptions_channels',
    sa.Column('tvsubchanid', npf.UInt32(), npd.Comment('TV subscription channel ID'), nullable=False, default=sa.Sequence('tv_subscriptions_channels_tvsubchanid_seq')),
    sa.Column('tvsubtid', npf.UInt32(), npd.Comment('TV subscription type ID'), nullable=False),
    sa.Column('tvchanid', npf.UInt32(), npd.Comment('TV channel ID'), nullable=False),
    sa.ForeignKeyConstraint(['tvchanid'], ['tv_channels.tvchanid'], name='tv_subscriptions_channels_fk_tvchanid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tvsubtid'], ['tv_subscriptions_types.tvsubtid'], name='tv_subscriptions_channels_fk_tvsubtid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tvsubchanid', name=op.f('tv_subscriptions_channels_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tv_subscriptions_channels', 'Subscription memberships for TV channels')
    op.create_index('tv_subscriptions_channels_i_tvchanid', 'tv_subscriptions_channels', ['tvchanid'], unique=False)
    op.create_index('tv_subscriptions_channels_u_link', 'tv_subscriptions_channels', ['tvsubtid', 'tvchanid'], unique=True)
    op.create_table('tv_cards_def',
    sa.Column('tvcardid', npf.UInt32(), npd.Comment('TV card ID'), nullable=False, default=sa.Sequence('tv_cards_def_tvcardid_seq')),
    sa.Column('aeid', npf.UInt32(), npd.Comment('Access entity ID'), nullable=False),
    sa.Column('tvsourceid', npf.UInt32(), npd.Comment('TV source ID'), nullable=False),
    sa.Column('extid', npf.ASCIIString(length=255), npd.Comment('TV card external ID'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('enabled', npf.NPBoolean(), npd.Comment('Is card enabled'), server_default=npf.npbool(True), nullable=False),
    sa.ForeignKeyConstraint(['aeid'], ['entities_access.entityid'], name='tv_cards_def_fk_aeid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tvsourceid'], ['tv_sources_def.tvsourceid'], name='tv_cards_def_fk_tvsourceid', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('tvcardid', name=op.f('tv_cards_def_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tv_cards_def', 'TV access cards')
    op.create_index('tv_cards_def_i_aeid', 'tv_cards_def', ['aeid'], unique=False)
    op.create_index('tv_cards_def_i_enabled', 'tv_cards_def', ['enabled'], unique=False)
    op.create_index('tv_cards_def_u_card', 'tv_cards_def', ['tvsourceid', 'extid'], unique=True)
    op.create_table('tv_subscriptions_def',
    sa.Column('tvsubid', npf.UInt32(), npd.Comment('TV subscription ID'), nullable=False, default=sa.Sequence('tv_subscriptions_def_tvsubid_seq')),
    sa.Column('tvsubtid', npf.UInt32(), npd.Comment('TV subscription type ID'), nullable=False),
    sa.Column('entityid', npf.UInt32(), npd.Comment('Entity ID'), nullable=False),
    sa.Column('aeid', npf.UInt32(), npd.Comment('Access entity ID'), nullable=False),
    sa.Column('epid', npf.UInt32(), npd.Comment('Paid service mapping ID'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['aeid'], ['entities_access.entityid'], name='tv_subscriptions_def_fk_aeid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entityid'], ['entities_def.entityid'], name='tv_subscriptions_def_fk_entityid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['epid'], ['paid_def.epid'], name='tv_subscriptions_def_fk_epid', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tvsubtid'], ['tv_subscriptions_types.tvsubtid'], name='tv_subscriptions_def_fk_tvsubtid', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('tvsubid', name=op.f('tv_subscriptions_def_pk')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.set_table_comment('tv_subscriptions_def', 'TV subscriptions')
    op.create_trigger('netprofile_tv', 'tv_subscriptions_def', 'before', 'insert', '1d7aad66a125')
    op.create_trigger('netprofile_tv', 'tv_subscriptions_def', 'before', 'update', '1d7aad66a125')
    op.create_trigger('netprofile_tv', 'tv_subscriptions_def', 'after', 'insert', '1d7aad66a125')
    op.create_trigger('netprofile_tv', 'tv_subscriptions_def', 'after', 'update', '1d7aad66a125')
    op.create_trigger('netprofile_tv', 'tv_subscriptions_def', 'after', 'delete', '1d7aad66a125')
    op.create_index('tv_subscriptions_def_i_entityid', 'tv_subscriptions_def', ['entityid'], unique=False)
    op.create_index('tv_subscriptions_def_i_tvsubtid', 'tv_subscriptions_def', ['tvsubtid'], unique=False)
    op.create_index('tv_subscriptions_def_u_epid', 'tv_subscriptions_def', ['epid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tv_subscriptions_def_u_epid', table_name='tv_subscriptions_def')
    op.drop_index('tv_subscriptions_def_i_tvsubtid', table_name='tv_subscriptions_def')
    op.drop_index('tv_subscriptions_def_i_entityid', table_name='tv_subscriptions_def')
    op.drop_table('tv_subscriptions_def')
    op.drop_index('tv_cards_def_u_card', table_name='tv_cards_def')
    op.drop_index('tv_cards_def_i_enabled', table_name='tv_cards_def')
    op.drop_index('tv_cards_def_i_aeid', table_name='tv_cards_def')
    op.drop_table('tv_cards_def')
    op.drop_index('tv_subscriptions_channels_u_link', table_name='tv_subscriptions_channels')
    op.drop_index('tv_subscriptions_channels_i_tvchanid', table_name='tv_subscriptions_channels')
    op.drop_table('tv_subscriptions_channels')
    op.drop_index('tv_channels_u_channel', table_name='tv_channels')
    op.drop_table('tv_channels')
    op.drop_index('tv_sources_def_u_name', table_name='tv_sources_def')
    op.drop_index('tv_sources_def_i_hostid', table_name='tv_sources_def')
    op.drop_table('tv_sources_def')
    op.drop_index('tv_subscriptions_types_u_name', table_name='tv_subscriptions_types')
    op.drop_index('tv_subscriptions_types_i_paidid', table_name='tv_subscriptions_types')
    op.drop_table('tv_subscriptions_types')
    # ### end Alembic commands ###

